coonu:
  aliyun:
    # 需在环境变量文件(.bash_profile)中配置:
    # ALIYUN_ACCESS_KEY_ID=xxxxxxx
    # ALIYUN_ACCESS_KEY_SECRET=xxxxxxxx
    # export ALIYUN_ACCESS_KEY_ID ALIYUN_ACCESS_KEY_SECRET
    access-key-id: ${aliyun_access_key_id}
    access-key-secret: ${aliyun_access_key_secret}
    dns:
      endpoint: alidns.cn-chengdu.aliyuncs.com

logging:
  level:
    # 可以针对不同包指定不同等级的日志;
    cn.coonu: debug
  file:
    name: logs/@project.artifactId@.log
    max-history: 30

spring:
  main:
    # 配置启动时banner的输出模式, 三种, 只在控制台输出, 控制台和日志输出, 关闭
    banner-mode: console
  banner:
    # 需要输出的banner文本文件;
    location: classpath:banner/banner.txt
    # 需要输出的banner图片文件, 会转换成艺术字输出;
#        image:
#            location: classpath:banner/lezz.png
